name: AI On-Demand Assistant  
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened]

jobs:
  ai-response:
    uses: ethereumfollowprotocol/workflow-automation/.github/workflows/issue-response.yml@v1.0.7
    with:
      config-profile: "backend"
      repository-config: ".github/ai-review-config.json"
      claude-code-action-ref: "0xthrpw/claude-code-action@v0.0.1"
      bot-mention: "@efp-dev-ops"
      enable-auto-labeling: true
      enable-escalation: true
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ALLOWED_USER_LIST: ${{ secrets.ALLOWED_USER_LIST }}
