name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    uses: ethereumfollowprotocol/workflow-automation/.github/workflows/pr-review.yml@v1.0.0
    with:
      config-profile: "default"
      enable-security-review: true
      enable-quality-review: true
      enable-documentation-review: true
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ALLOWED_USER_LIST: ${{ secrets.ALLOWED_USER_LIST }}