name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    uses: ethereumfollowprotocol/workflow-automation/.github/workflows/pr-review.yml@v1.0.7
    with:
      config-profile: "backend"
      repository-config: ".github/ai-review-config.json"
      claude-code-action-ref: "0xthrpw/claude-code-action@v0.0.1"
      enable-security-review: true
      enable-quality-review: true
      enable-documentation-review: true
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ALLOWED_USER_LIST: ${{ secrets.ALLOWED_USER_LIST }}
